[[ $- == *i* ]] || return

export PATH="$PATH:/etc/nixos/scripts"

eval "$(starship init bash)"
eval "$(direnv hook bash)"

alias ea='NVIM_APPNAME=astro-nvim nvim'
alias e='NVIM_APPNAME=ink-nvim nvim'
