export PATH="$PATH:/etc/nixos/scripts"
export PATH="$PATH:/etc/nixos/bins"


eval "$(starship init bash)"
eval "$(direnv hook bash)"
eval "$(zoxide init bash)"

alias ea='NVIM_APPNAME=astro-nvim nvim'
alias e='NVIM_APPNAME=ink-nvim nvim'
